# Generated by Django 5.2.5 on 2025-08-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country name", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City name", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street", max_length=100, verbose_name="street"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        help_text="House number",
                        max_length=50,
                        verbose_name="house_number",
                    ),
                ),
            ],
            options={
                "verbose_name": "контактная информация",
                "verbose_name_plural": "контактные информации",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Product name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Product model", max_length=100, verbose_name="model"
                    ),
                ),
                ("launched_at", models.DateField(verbose_name="launched product date")),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Vendor name",
                        max_length=150,
                        verbose_name="vendor title",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        help_text="Vendor level",
                        verbose_name="vendor level",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="debt to supplier",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.contactinfo",
                        verbose_name="contacts",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="products",
                        to="trading.product",
                        verbose_name="products",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading.vendor",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "поставщик",
                "verbose_name_plural": "поставщики",
            },
        ),
    ]
