# Generated by Django 5.2.5 on 2025-08-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "ordering": ["id"],
                "verbose_name": "контактная информация",
                "verbose_name_plural": "контактные информации",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["id"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
